### PR TITLE
Tenant form validations

### LINKED ISSUE #152: Add validations in create clusters modal
Create clusters modal needs to have validations in the inputs

### PR DESCRIPTION
**Pull request by bexsoft**
fixes #152 

## What does this do?

Implement validations in create tenant form

Screen Shot 2020-06-17 at 1 54 38 PM
Screen Shot 2020-06-17 at 1 54 31 PM

### CODE REVIEW

**Comment by cesnietor** [comment]
should we do a suggestion on `Image` e.g. "minio/minio:<version>" as shadow or something  since I think it was not working with only the version.

**Comment by dvaldivia** [comment]
@cesnietor we could have it be the placeholder maybe

**Comment by bexsoft** [comment]
Yeah, we can put this information as a placeholder

**Comment by bexsoft** [comment]
@dvaldivia @cesnietor PR updated with requested changes
Screen Shot 2020-06-17 at 8 31 38 PM

**Pull request merged**
