### PR TITLE
Configuration forms

### PR DESCRIPTION
**Pull request by bexsoft**
## What does this do?
Implements forms (UI) for settings page:
- region
- cache
- compression
- etcd
- identity_openid
- identity_ldap
- policy_opa
- logger_webhook
- audit_webhook

Fixes a Memory leak in Configuration pages / Lambda Notification pages
Implements page for webhooks

NOTE: These forms are not connected to API yet

## How to test

- Go into configurations list, check the forms that work as expected without re-renders / hangs
- Simulate a send configuration & check that all the information in the form is in the headers
- Go into Lambda Notifications page & check that forms are working as expected

### CODE REVIEW

**Comment by cesnietor** [comment]
When it failed on put, the loading remained:
Screen Shot 2020-04-29 at 2 05 45 PM

**Comment by cesnietor** [comment]
When the configuration has something the UI is not showing the info. Is that part of this PR?
```
./mc admin config get myminio region               
region name=us-west 
```
Screen Shot 2020-04-29 at 2 12 41 PM

**Comment by bexsoft** [comment]
> When the configuration has something the UI is not showing the info. Is that part of this PR?
> 
> ```
> ./mc admin config get myminio region               
> region name=us-west 
> ```
> 
> Screen Shot 2020-04-29 at 2 12 41 PM

No, This PR only include the forms, no connections are done yet

**Comment by bexsoft** [comment]
Updated PR description

**Comment by bexsoft** [comment]
Fixed issue with forms data
Screen Shot 2020-04-29 at 9 21 14 PM

**Pull request merged**
