### PR TITLE
Tables replacement in mcs

### PR DESCRIPTION
**Pull request by bexsoft**
## What does this do?

Replaced all the tables in mcs to be consistent with the new design

## How to test

Go into each section and check that all the information is shown correctly and the table interactions doesn't get broken

### CODE REVIEW

**Comment by cesnietor** [comment]
Not sure if part of this pr. when there is no group selected on creation of a user the group parameter needs to be sent as empty `[]`
Screen Shot 2020-04-21 at 11 31 35 AM

**Comment by cesnietor** [comment]
After deletion of a user the page doesn't update:
Screen Shot 2020-04-21 at 11 32 25 AM
Screen Shot 2020-04-21 at 11 32 31 AM

**Comment by cesnietor** [comment]
When a bucket is deleted an error occurs:
To reproduce this I only had one bucket and deleted it.
Screen Shot 2020-04-21 at 11 32 51 AM

**Comment by cesnietor** [comment]
After deletion of a single bucket, the page doesn't load.
Screen Shot 2020-04-21 at 11 35 05 AM

**Comment by bexsoft** [comment]
> Not sure if part of this pr. when there is no group selected on creation of a user the group parameter needs to be sent as empty `[]`
> Screen Shot 2020-04-21 at 11 31 35 AM

Seems like mc is now returning null when the users list is empty instead of an empty array like it used to do before. Fixed issue

**Comment by bexsoft** [comment]
> After deletion of a user the page doesn't update:
> Screen Shot 2020-04-21 at 11 32 25 AM
> After delete:
> Screen Shot 2020-04-21 at 11 32 31 AM

This seems to be an old issue, it only happens when you have one only one user in the list and you want to delete it, Will file a new issue for this

**Comment by bexsoft** [comment]
> When I try to edit a bucket this breaks.
> Screen Shot 2020-04-21 at 11 32 51 AM

Fixed. same issue as cannot update user

**Comment by bexsoft** [comment]
> After deletion of a single bucket, the page doesn't load.
> Screen Shot 2020-04-21 at 11 35 05 AM

Fixed

**Pull request merged**
